In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.23.5'

In [ ]:
# Criando arrays numpy (array == lista)
arrl = np.array([10,20,30,40,50,60,70,80,90])
print(arrl)
type(arrl)

[10 20 30 40 50 60 70 80 90]


numpy.ndarray

In [ ]:
# Verificando o formato do array
arrl.shape
# Esse (9,) significa que é um array em 1d com 9 elementos (um vetor)
# existe o 2d e 3d
# eixos x,y,z

(9,)

In [ ]:
# Imprimindo um elemento do array
arrl[4] # (Indice 4)
arrl[1:4] # Indices entre 1' e 3' - excluindo o 4 ;; o ultimo valor é exclusivo.
indices = [1,2,5,7]
arrl[indices]
# Criando uma mascará para numeros pares


array([20, 30, 60, 80])

In [ ]:
# Criando uma mascará para numeros pares
mask = (arrl % 2 == 0)
mask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
arrl[mask]

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2
type(arr2)

numpy.ndarray

In [ ]:
# Soma acumulada do array
arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [ ]:
# Crie um array com os parametros (inicio, fim, intervalo) - start, stop, step
arr3 = np.arange(0,50,5)
arr3

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
# Cria uma matriz binária preenchendo com 1 somente a diagonal
arr5 = np.eye(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Tipo dos dados.
print(arr3.dtype)

int64


In [ ]:
arr6 = np.diag(np.array([1,2,3,4]))
arr6

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
# Cria um array de numeros espaçados igualmente dentro do intervalo definido
# (Inicio, Fim, Qntd de numeros)
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Cria um array de numeros aleatórios dentro do intervalo escolhido em função logaritmica
print(np.logspace(0,1))

[ 1.          1.04811313  1.09854114  1.1513954   1.20679264  1.26485522
  1.32571137  1.38949549  1.45634848  1.52641797  1.59985872  1.67683294
  1.75751062  1.84206997  1.93069773  2.02358965  2.12095089  2.22299648
  2.32995181  2.44205309  2.55954792  2.6826958   2.8117687   2.9470517
  3.0888436   3.23745754  3.39322177  3.55648031  3.72759372  3.90693994
  4.09491506  4.29193426  4.49843267  4.71486636  4.94171336  5.17947468
  5.42867544  5.68986603  5.96362332  6.25055193  6.55128557  6.86648845
  7.19685673  7.54312006  7.90604321  8.28642773  8.68511374  9.10298178
  9.54095476 10.        ]


In [ ]:
# Manipulando matrizes numpy
arr9 = np.array([[1,2,3],[4,5,6]])
arr9

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
type(arr9)
arr9.shape
# array em 2d, 2 linhas e 3 colunas

(2, 3)

In [ ]:
arr10 = np.ones((2,5))
arr10

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Operações matemáticas: matrix
# Armazenamento de dados: array

In [ ]:
lista = [[1,2,3],[10,20,30],[100,200,300]]
arr11 = np.matrix(lista)
arr11

matrix([[  1,   2,   3],
        [ 10,  20,  30],
        [100, 200, 300]])

In [ ]:
np.shape(arr11)

(3, 3)

In [ ]:
np.size(arr11)

9

In [ ]:
arr11[2,1]

200

In [ ]:
arr11[0:2,2]

matrix([[ 3],
        [30]])

In [ ]:
arr11[1,]

matrix([[10, 20, 30]])

In [ ]:
# Cria um array numpy de 3 dimensões
arr_3d = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

In [ ]:
arr_3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
# Cria um array numpy de 4 dimensões
arr_4d = np.array([
    [
        [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10],
            [11, 12, 13, 14, 15],
            [16, 17, 18, 19, 20]
        ],
        [
            [21, 22, 23, 24, 25],
            [26, 27, 28, 29, 30],
            [31, 32, 33, 34, 35],
            [36, 37, 38, 39, 40]
        ],
        [
            [41, 42, 43, 44, 45],
            [46, 47, 48, 49, 50],
            [51, 52, 53, 54, 55],
            [56, 57, 58, 59, 60]
        ]
    ],
    [
        [
            [61, 62, 63, 64, 65],
            [66, 67, 68, 69, 70],
            [71, 72, 73, 74, 75],
            [76, 77, 78, 79, 80]
        ],
        [
            [81, 82, 83, 84, 85],
            [86, 87, 88, 89, 90],
            [91, 92, 93, 94, 95],
            [96, 97, 98, 99, 100]
        ],
        [
            [101, 102, 103, 104, 105],
            [106, 107, 108, 109, 110],
            [111, 112, 113, 114, 115],
            [116, 117, 118, 119, 120]
        ]
    ]
])

In [ ]:
print(arr_4d)

[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]]

  [[ 21  22  23  24  25]
   [ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]]

  [[ 41  42  43  44  45]
   [ 46  47  48  49  50]
   [ 51  52  53  54  55]
   [ 56  57  58  59  60]]]


 [[[ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]
   [ 76  77  78  79  80]]

  [[ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]

  [[101 102 103 104 105]
   [106 107 108 109 110]
   [111 112 113 114 115]
   [116 117 118 119 120]]]]


In [ ]:
import os
filename = os.path.join('dataset.csv')

In [ ]:
# No Windows use !more dataset.csv. Mac ou Linux use !head dataset.csv
#!head dataset.csv
!more dataset.csv

sepal_length,sepal_width,petal_length,petal_width,species
5.1,3.5,1.4,0.2,setosa
4.9,3,1.4,0.2,setosa
4.7,3.2,1.3,0.2,setosa
4.6,3.1,1.5,0.2,setosa
5,3.6,1.4,0.2,setosa
5.4,3.9,1.7,0.4,setosa
4.6,3.4,1.4,0.3,setosa
5,3.4,1.5,0.2,setosa
4.4,2.9,1.4,0.2,setosa
4.9,3.1,1.5,0.1,setosa
5.4,3.7,1.5,0.2,setosa
4.8,3.4,1.6,0.2,setosa
4.8,3,1.4,0.1,setosa
4.3,3,1.1,0.1,setosa
5.8,4,1.2,0.2,setosa
5.7,4.4,1.5,0.4,setosa
5.4,3.9,1.3,0.4,setosa
5.1,3.5,1.4,0.3,setosa
5.7,3.8,1.7,0.3,setosa
5.1,3.8,1.5,0.3,setosa
5.4,3.4,1.7,0.2,setosa
5.1,3.7,1.5,0.4,setosa


In [ ]:
# Carregando um dataset para dentro de um array
arr13 = np.loadtxt(filename, delimiter = ',', usecols = (0,1,2,3), skiprows = 1)

In [ ]:
arr13